### ISSUE TITLE
Update to Mendix 6

### ISSUE THREAD

**Issue by CharlesBronzwaer** [mendix/InputReferenceSelector#1]
This widget cannot be used in Mendix 6.

**Comment by nvwieren** [comment]
Are there any plans to upgrade this widget any time soon?
Thanks,
Nick

**Comment by RoelandSalij** [comment]
We have a planned a new release in the coming 2 weeks (before 25th of december)

**Comment by JelteMX** [comment]
@CharlesBronzwaer @nvwieren Could both of you test the development version? You can download it here: https://github.com/mendix/InputReferenceSelector/raw/development/test/widgets/refkit.mpk

I updated the code and should work properly in MX6 (tested that myself). I will update the widget in the AppStore as soon as I have feedback from you :-)

**Comment by CharlesBronzwaer** [comment]
![image](https://cloud.githubusercontent.com/assets/9037252/11746328/f1af9f56-a01d-11e5-8aa1-929b0edfd81a.png)
I get this error when I open the page. There are no errors in the Mendix console. I do see this error in the Chrome Consolse
![image](https://cloud.githubusercontent.com/assets/9037252/11746357/215fd392-a01e-11e5-84f9-d910f3151f64.png)

**Comment by JelteMX** [comment]
Thanks, I'll look into it. It has something to do with lib/XpathSource I guess, I have seen it before (and thought I fixed it)

**Comment by JelteMX** [comment]
I think I found the issue. Can you download the widget again, using the link I provided earlier? This should fix the issue with .resize method missing

**Comment by CharlesBronzwaer** [comment]
Seems to work, tnx!

**Comment by JelteMX** [comment]
Great! Thanks for the feedback :-)

**Comment by CharlesBronzwaer** [comment]
Hi Jelte,

I found two additional issues with the widget.
1. We get an NullPointerException error when we use an on change microflow. We get this error when the user changes the value of the InputRefSelector when an on change MF is configured in the widget properties:
   java.lang.NullPointerException: null
               at com.mendix.webui.actions.client.ExecuteAction.execute(ExecuteAction.java:56)
               at com.mendix.webui.requesthandling.ClientRequestHandler$$anonfun$handleRequest$1.apply$mcV$sp(ClientRequestHandler.scala:322)
               at com.mendix.webui.requesthandling.ClientRequestHandler$$anonfun$handleRequest$1.apply(ClientRequestHandler.scala:315)
               at com.mendix.webui.requesthandling.ClientRequestHandler$$anonfun$handleRequest$1.apply(ClientRequestHandler.scala:315)
               at com.mendix.core.session.Worker$$anonfun$receive$3$$anonfun$2$$anon$1.execute(ActionDispatching.scala:145)
               at com.mendix.util.classloading.Runner.doRunUsingClassLoaderOf(Runner.java:32)
               at com.mendix.core.session.Worker$$anonfun$receive$3$$anonfun$2.apply(ActionDispatching.scala:147)
               at scala.util.Try$.apply(Try.scala:191)
               at com.mendix.core.session.Worker$$anonfun$receive$3.applyOrElse(ActionDispatching.scala:141)
               at akka.actor.Actor$class.aroundReceive(Actor.scala:465)
               at com.mendix.core.session.Worker.aroundReceive(ActionDispatching.scala:137)
               at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516)
               at akka.actor.ActorCell.invoke(ActorCell.scala:487)
               at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:238)
               at akka.dispatch.Mailbox.run(Mailbox.scala:220)
               at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:393)
               at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
               at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
               at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
               at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
2. It is not possible to add a validation feedback to the widget. The feedback is shown in a popup in stead of beneath the inputRefSelector field.

**Comment by JelteMX** [comment]
@CharlesBronzwaer I'll create a seperate issue for this, update the widget in the AppStore and close this one. 

Not sure if issue 1 is due to the widget or has something to do with the microflow. Issue 2 can be easily fixed I guess

**Comment by CharlesBronzwaer** [comment]
It is a really simple MF that just refreshes the object. When I put the MF on the page as a button it works fine. It seems the MF isn't being triggered because it not possible to debug with breakpoints.

**Comment by JelteMX** [comment]
If you have a test-project that I can work with, I might be able to debug it. Can you send one to community[at]mendix.com? If you mention me, I'll have a look at it.

**Comment by CharlesBronzwaer** [comment]
I've mailed a test project to the mentioned address. Thanks!

**Comment by JelteMX** [comment]
@CharlesBronzwaer concerning both issues, I have opened a new issue: https://github.com/mendix/InputReferenceSelector/issues/2
