### ISSUE TITLE
Two issues with new version of InputReferenceSelector

### ISSUE THREAD

**Issue by JelteMX** [mendix/InputReferenceSelector#2]
Ticket filed by : @CharlesBronzwaer 

1.) We get an NullPointerException error when we use an on change microflow. We get this error when the user changes the value of the InputRefSelector when an on change MF is configured in the widget properties:
java.lang.NullPointerException: null
at com.mendix.webui.actions.client.ExecuteAction.execute(ExecuteAction.java:56)
at com.mendix.webui.requesthandling.ClientRequestHandler$$anonfun$handleRequest$1.apply$mcV$sp(ClientRequestHandler.scala:322)
at com.mendix.webui.requesthandling.ClientRequestHandler$$anonfun$handleRequest$1.apply(ClientRequestHandler.scala:315)
at com.mendix.webui.requesthandling.ClientRequestHandler$$anonfun$handleRequest$1.apply(ClientRequestHandler.scala:315)
at com.mendix.core.session.Worker$$anonfun$receive$3$$anonfun$2$$anon$1.execute(ActionDispatching.scala:145)
at com.mendix.util.classloading.Runner.doRunUsingClassLoaderOf(Runner.java:32)
at com.mendix.core.session.Worker$$anonfun$receive$3$$anonfun$2.apply(ActionDispatching.scala:147)
at scala.util.Try$.apply(Try.scala:191)
at com.mendix.core.session.Worker$$anonfun$receive$3.applyOrElse(ActionDispatching.scala:141)
at akka.actor.Actor$class.aroundReceive(Actor.scala:465)
at com.mendix.core.session.Worker.aroundReceive(ActionDispatching.scala:137)
at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516)
at akka.actor.ActorCell.invoke(ActorCell.scala:487)
at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:238)
at akka.dispatch.Mailbox.run(Mailbox.scala:220)
at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:393)
at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

2.) It is not possible to add a validation feedback to the widget. The feedback is shown in a popup in stead of beneath the inputRefSelector field.

**Comment by JelteMX** [comment]
@CharlesBronzwaer I reproduced issue 1. Have fixed it in this version: https://github.com/mendix/InputReferenceSelector/raw/master/test/widgets/refkit.mpk, will you test that one?

**Comment by CharlesBronzwaer** [comment]
Issue 1 is tested and ok. Tnx! Did you have time to reproduce issue 2?

**Comment by JelteMX** [comment]
Yes. This should be fixed soon. Thanks for testing, will let you know when I fixed issue 2

**Comment by JelteMX** [comment]
Second issue is also solved. Tested this with your test-project as well. Thanks for reporting the issues! I have submitted an update to the AppStore, should be updated there in a day or two.
